"""Write the numeric/data change list (markdown) from the analysis outputs."""
import json
T = json.load(open("tables.json")); R = json.load(open("analysis_dsi_results.json")); ML = json.load(open("analysis_ml_results_id.json")); MLF = json.load(open("analysis_ml_results.json"))
P = json.load(open("analysis_ml2_partial_id.json")); XGB = json.load(open("xgb_id.json")); SH = json.load(open("shap_id.json")); U = json.load(open("fig21_numbers.json"))
V = R["val"]; hv = R["heur_val"]; hd = R["heur_vs_dsi"]; rw = R["r220"]["rows"]; NS = T["novel_stats"]; r216 = ML["r216"]; RD = R["r221"]
t2 = P["table2"]; t3 = P["table3"]
def f(x, n=3): return f"{x:.{n}f}"
L = []
L.append("# Numeric and data changes: original submission vs revision\n")
L.append("Every revised value below was produced by the scripts in `revision_code/` on the cached Materials Project data (identical document counts to the original run: 2,774 electrodes, 16,510 Li-O structures). 'Original' is the value in the submitted main.tex; 'notebook' is the value printed in the author's Colab notebook (`Copy_of_CathodeAI_complete_clean.ipynb`) where it differs from the manuscript. Spot-check instructions are given per block.\n")
L.append("## 1. Dataset definition\n")
L.append("| Item | Original | Revised | Reason |\n|---|---|---|---|")
L.append("| ML dataset | 1,702 entries, formula-level merge (descriptors averaged over all structural entries sharing the Li-stripped base formula) | 1,724 entries, identifier-level merge (descriptors of each electrode's own discharged end-member) | R2.15; formula-level merge averaged polymorphs and Li stoichiometries |")
L.append("| Match rate | 90.2 % of 1,886 | 91.4 % of 1,886 | same |")
L.append("| Entries with polymorph-averaged descriptors | 1,415 of 1,702 (not disclosed) | 0 | same |")
L.append("| Discovery zone | '12 to 15 materials', no definition | 26 unique compositions (39 entries): top-quartile composite (>= 0.717), E_hull(discharged) < 50 meV/atom, top-quartile ED (>= 2,399 Wh/L) | defined explicitly |")
L.append("| Entries with computable DSI | not stated | 787 of 813 (26 H-containing entries lack a structural document) | new |\n")
L.append("## 2. Table 2 (feature sets), random / grouped 5-fold CV R2\n")
L.append("| Feature set | Original (random only) | Notebook (random) | Revised random | Revised grouped |\n|---|---|---|---|---|")
orig2 = {"Electrochemical only": "0.857 +/- 0.019", "Structural only (DFT)": "0.364 +/- 0.024", "Combined (final)": "0.942 +/- 0.056", "MatMiner (Magpie)": "0.413 +/- 0.016", "Lasso-selected": "0.413 +/- 0.017 (83 features)", "Full (combined + MatMiner)": "0.937 +/- 0.055"}
nb2 = {"Electrochemical only": "0.8578 +/- 0.0338", "Structural only (DFT)": "0.3366 +/- 0.0851", "Combined (final)": "0.9392 +/- 0.0575", "MatMiner (Magpie)": "0.4048 +/- 0.0842", "Lasso-selected": "0.4059 +/- 0.0831 (83)", "Full (combined + MatMiner)": "0.9312 +/- 0.0630"}
for k in orig2: L.append(f"| {k} | {orig2[k]} | {nb2[k]} | {f(t2[k]['r2'])} +/- {f(t2[k]['std'])} ({t2[k]['nfeat']} features) | {f(t2[k]['r2g'])} +/- {f(t2[k]['stdg'])} |")
b = ML["r213"]
L.append(f"| V, C only (RF) | -- | -- | {f(b['V + C only'][0])} +/- {f(b['V + C only'][1])} | -- |")
L.append(f"| V, C, rho only (RF) | -- | -- | {f(b['V + C + density'][0])} +/- {f(b['V + C + density'][1])} | -- |")
L.append(f"| log-linear V, C, rho | -- | -- | {f(b['V + C + density (linear on log)'][0])} | -- |")
L.append(f"| V x C x rho unfitted | 0.985 (Section 2.3) | 0.9849 | {b['arith']:.4f} | -- |\n")
L.append("Spot-check: `STATE=repro_state_id.pkl TAG=_id python3 analysis_ml.py` (R1.3 and R2.13 blocks) and the Table 2 block of `analysis_ml2.py`.\n")
L.append("## 3. Table 3 (architectures on combined 8 features)\n")
L.append("| Model | Original R2 / std / MAE | Notebook | Revised random R2 / std / MAE | Revised grouped R2 / MAE |\n|---|---|---|---|---|")
orig3 = {"Linear Regression": ("0.930 / 0.015 / 153.99", "0.9286 / 0.0193 / 153.60"), "Random Forest": ("0.942 / 0.056 / 101.97", "0.9392 / 0.0575 / 101.10"), "XGBoost": ("0.945 / 0.046 / 104.28", "0.9362 / 0.0517 / 104.87"), "Neural Network": ("0.976 / 0.010 / 84.46", "0.9736 / 0.0134 / 83.64")}
for k in ["Linear Regression", "Random Forest", "XGBoost", "Neural Network"]:
    v = XGB if k == "XGBoost" else t3[k]
    L.append(f"| {k} | {orig3[k][0]} | {orig3[k][1]} | {f(v['r2'])} / {f(v['std'])} / {v['mae']:.1f} | {f(v['r2g'])} / {v['maeg']:.1f} |")
L.append("| Held-out split (RF) | R2 0.966, MAE 92.9 | R2 0.9653, MAE 97.9 (formula-level) | R2 0.865, MAE 88.5 (ID-level split; text explains) | |\n")
L.append("## 4. Table 4 (SHAP, RF 200 trees on all entries)\n")
L.append("| Feature | Original mean abs SHAP / importance % | Notebook | Revised |\n|---|---|---|---|")
orig4 = {"Capacity (mAh/g)": ("602.27 / 78.5", "603.36"), "Avg Voltage (V)": ("205.73 / 7.9", "203.91"), "Density (g/cc)": ("188.54 / 8.7", "191.36"), "Volume per Atom (A3)": ("34.93 / 1.4", "31.05"), "Formation Energy (eV/atom)": ("22.74 / 1.7", "23.61"), "Band Gap (eV)": ("4.70 / 1.3", "5.09"), "Energy Above Hull (eV)": ("4.33 / 0.4", "4.09"), "N Elements": ("1.81 / 0.1", "1.84")}
for k in orig4: L.append(f"| {k} | {orig4[k][0]} | {orig4[k][1]} | {SH[k]['mean_abs_shap']:.2f} / {SH[k]['rf_importance']*100:.1f} |")
L.append("\n## 5. Section 2.3 (arithmetic relation and missing data)\n")
L.append("| Item | Original | Revised |\n|---|---|---|")
L.append(f"| V x C x rho vs MP energy density | R2 0.985 | R2 {b['arith']:.4f}; k = {ML['r214']['k']:.4f}; median ratio {ML['r214']['median_ratio']:.4f}. Formula-level data: single-structure rows R2 {MLF['r214']['r2_single']:.4f}, averaged rows {MLF['r214']['r2_multi']:.4f} |")
L.append(f"| 30 % missing capacity | 'ML covers 100 % (R2 0.986)'; mask never applied in code | held-out complete rows R2 {f(r216['test_complete'])} (n={r216['n_test_complete']}); imputed rows {f(r216['test_imputed'])} (n={r216['n_test_imp']}); arithmetic with mean-imputed C {f(r216['arith_mean_imp'])}; arithmetic with RF-imputed C {f(r216['arith_rf_imp'])}; ML with RF-imputed C {f(r216['ml_rf_imp'])}; capacity imputation R2 {f(r216['cap_imp_r2'])} |")
L.append("| Arithmetic coverage | '~69 %' | unchanged concept, stated as 70 % of rows have observed capacity |\n")
L.append("## 6. Section 2.5 (heuristic, DSI, polymorphs)\n")
L.append("| Item | Original | Revised |\n|---|---|---|")
L.append(f"| Heuristic vs structure indicator | Pearson r = 0.151 (metal lookup vs volume-strain bins, 569 formulas) | metal lookup vs DSI: Spearman {hd[1]:.3f}, Pearson {hd[0]:.3f} (n = {hd[2]} entries; per unique formula {R['heur_vs_dsi_formula'][1]:.3f} / {R['heur_vs_dsi_formula'][0]:.3f}, n = {R['heur_vs_dsi_formula'][2]}) |")
L.append(f"| Metal-identity heuristic vs experiment (n=11) | not reported | rho {f(hv['rho_nostab'])} (p {f(hv['p_nostab'])}) without stability factor; {f(hv['rho_stab'])} (p {f(hv['p_stab'])}) with |")
L.append(f"| DSI vs experiment | rho 0.760, p 0.007 (bins) | unchanged: {f(V['rho_bins'])}, p {f(V['p_bins'])} (categories); continuous score {f(V['rho_cont'])}, p {f(V['p_cont'])} |")
L.append(f"| Single descriptor | rho 0.549, p 0.080 | unchanged {f(V['rho_single'])}, {f(V['p_single'])} |")
L.append("| Bootstrap CIs | [0.509, 0.934] / [0.018, 0.923] | unchanged (reproduced exactly) |")
L.append("| LOO | DSI [0.680, 0.848] vs [0.396, 0.706], 11/11 | unchanged (reproduced exactly) |")
L.append("| Weight schemes | rho in [0.529, 0.768], 5/6 | unchanged (reproduced exactly) |")
L.append(f"| Nested LOO weight optimisation | not reported | rho {V['nested']['rho']:.3f} (p {V['nested']['p']:.3f}); in-sample optimum {f(V['nested']['insample_best'][0])}; full grid median {f(V['sweep'][0])}, range [{f(V['sweep'][1])}, {f(V['sweep'][2])}], {V['sweep'][3]*100:.0f} % above baseline |")
L.append(f"| Stratified | not reported | layered n=7: {f(V['strat']['layered oxides'][1])} (p {f(V['strat']['layered oxides'][2])}) categories, {f(V['strat']['layered oxides cont'][1])} (p {f(V['strat']['layered oxides cont'][2])}) continuous, single {f(V['strat']['layered oxides'][3])}; non-layered n=4: all category A |")
L.append(f"| Without LTO | not reported | DSI {f(V['no_lto'][0])} (p {f(V['no_lto'][1])}); single {f(V['no_lto'][2])} (p {f(V['no_lto'][3])}) |")
L.append("| Li2MnO3 at 15 cycles | not reported | no rank change; rho unchanged |")
L.append("| Table 7 columns | Exp cycles, Single (cycles), DSI (cycles), Error % | Exp cycles (rank only), heuristic cycles, single category, DSI score, DSI category; Error column removed |")
L.append("| '90.9 % binary accuracy (10/11)' | kept | kept (10/11, category B or better vs >= 500 cycles) |")
L.append("| 'Prediction error 10-47 % in olivines' | present | removed (implied absolute prediction) |")
pol = {r["Space Group"]: r for r in R["polymorph"]}
L.append(f"| LiCuO2 polymorphs | 'seven-fold, 225-1650 cycles' (text) / 300-2200 (figure), strain proxy | 3 of 8 polymorphs are electrode end-members: C2/m dV/V {pol['C2/m']['dV/V (%)']:.1f} %, E_hull,charge {pol['C2/m']['E_hull charge (eV)']*1000:.0f} meV, DSI {pol['C2/m']['DSI']:.2f} (D); R-3m {pol['R-3m']['dV/V (%)']:.1f} %, {pol['R-3m']['E_hull charge (eV)']*1000:.0f} meV, DSI {pol['R-3m']['DSI']:.2f} (C); Cm {pol['Cm']['dV/V (%)']:.1f} %, {pol['Cm']['E_hull charge (eV)']*1000:.0f} meV, DSI {pol['Cm']['DSI']:.2f} (B). Static columns of Table 5 unchanged (reproduced exactly) |")
L.append(f"| DFT-error sensitivity | 'does not affect relative rankings' | validation rho median {f(RD['val_rho_med'])}, 5-95 % [{f(RD['val_rho_5'])}, {f(RD['val_rho_95'])}]; {RD['cat_flip_813']*100:.1f} % category changes across 813 set; Pareto Jaccard EV {RD['jac_ev']:.2f}, grid {RD['jac_grid']:.2f}; {ML['r221']['near_thresh']} of 1,724 within 24 meV of 50 meV threshold; zone flips {ML['r221']['flip_frac']*100:.1f} % per draw |\n")
L.append("## 7. Section 2.7 (phosphates, Pareto, price)\n")
L.append("| Item | Original | Revised |\n|---|---|---|")
L.append(f"| Group sizes | n = 312 vs 1,390 (stated); test 'Welch' | n = {R['r220']['n_po4']} vs {R['r220']['n_non']} (813 oxide set, as in the code); Welch and Mann-Whitney |")
for lab, k in [("Thermal safety", "Thermal Safety Score"), ("Thermal safety, no bonus", "Thermal Safety Score (no PO4 bonus)"), ("DSI", "DSI"), ("DSI, no bonus", "DSI (no PO4 bonus)"), ("Heuristic cycles", "Estimated Cycles"), ("Heuristic cycles, no 1.30 factor", "Estimated Cycles (no PO4 factor)"), ("Energy density", "Energy Density (Wh/L)"), ("Solid-state score", "Solid State Score"), ("dV/V", "Max Volume Change (%)"), ("E_hull,charge", "Stability Charge (eV)")]:
    a, bb, p, pu = rw[k][:4]
    orig = {"Thermal safety": "0.803 vs 0.688", "Heuristic cycles": "890 vs 742 (Table 8 'Predicted cycle life')", "Energy density": "1692 vs 1955", "Solid-state score": "0.895 vs 0.935"}.get(lab, "not reported")
    L.append(f"| {lab} | {orig} | {a:.3f} vs {bb:.3f}; Welch p {p:.2e}; MWU p {pu:.2e} |")
L.append(f"| Pareto fronts (top-100 by composite, DSI axis) | EV front listed by heuristic cycles; grid: Li1-2Ti(PO3)5 sole | EV: {', '.join(x['Formula'] for x in R['pareto']['EV: ED vs DSI'])}; consumer: {', '.join(x['Formula'] for x in R['pareto']['Consumer: ED vs cost'])}; grid: {', '.join(x['Formula'] for x in R['pareto']['Grid: thermal vs DSI'])} |")
L.append(f"| Price scenarios | Li0-1CuO2 rank 1 in 5/5 | unchanged (Section 32 protocol): top-5 per scenario {R['price']} |\n")
L.append("## 8. Section 2.8 (generated compositions)\n")
L.append("| Item | Original | Revised |\n|---|---|---|")
L.append(f"| Novelty query | Li-index-stripped formulas | reduced formulas as generated |")
L.append(f"| Unique compositions | 42 (not reduced) | {NS['n_rows']} generated rows, {NS['n_unique']} unique reduced compositions |")
L.append(f"| Synthesizability | 27/42 (64 %) < 50 meV; 6 unlikely; 8 unique absent | {NS['n_present_unique']} unique present ({NS['n_present_rows']} rows); {NS['lt50_unique']} unique < 50 meV ({NS['onhull_unique']} on hull); {NS['mid_unique']} between 50 and 100; 0 above 100; {len(NS['absent'])} absent: {', '.join(NS['absent'])} |")
L.append(f"| Original 'absent' compositions now found present | -- | {NS['orig_absent_now_present']} (stripped query, correct formula, E_hull meV) |")
L.append(f"| Table 9 predicted ED | 3901.5, 4090.3, 3969.9, 3809.7, 3497.3, 3992.6, 3050.7, 3093.3 (LiCu2O3 ... LiV2O6) | rebuilt for the {len(NS['absent'])} absent compositions from the reproduced 4-feature RF (see Table 9); all 42 predictions in ESI Table S3; range {NS['ed_min']:.0f}-{NS['ed_max']:.0f} |")
L.append("| Prediction model | 'structural descriptors alone' (2.3) / '8-feature RF' (Table S2) | 4-feature electrochemical RF with assigned inputs (as executed) |")
L.append("| Applicability domain | leverage on hand-entered 8-feature vectors for LiNiO2, LiFe2O4, LiVO3, LiCuO2 (LiFe2O4 marginal, Z 4.47) | 4-feature space actually used: max |Z| 2.06, max leverage 0.0038 < 0.0080, all 42 in domain |")
L.append("| UMAP | 1,702 known + 42 | 1,724 known + 42 (regenerated) |\n")
L.append("## 9. Section 2.9 (uncertainty)\n")
L.append(f"| Item | Original | Notebook | Revised |\n|---|---|---|---|\n| 95 % coverage | 95.6 % | 95.6 % | {U['coverage']:.1f} % (n = {U['n']}) |\n| Mean half-width | 308 Wh/L | 323.6 | {U['mean_hw']:.0f} Wh/L |\n| r(half-width, capacity) | 0.555 | 0.620 | {U['r']:.3f} |\n")
L.append("## 10. Table 10\n")
L.append("Original rows (metal-identity cycles; formulas mis-transcribed, e.g. Li0.1CuO2; ranks 11 and 12 of the notebook skipped): Li0-1CuO2 320 / 0.827; Li0-1CuO 180 / 0.821; Li0-2CuPO4 484 / 0.798; Li0-0.33CuO 162 / 0.785; Li0-5Mn3Cu(PO4)4 1109 / 0.780; Li0-1MnO2 633 / 0.779; Li0-5Mn2(PO4)3 943 / 0.777; Li0-2Mn3CuO8 732 / 0.775; Li0-1CuPO4 639 / 0.773; Li1-5Mn2(PO4)3 1156 / 0.769. All ten original composite scores were reproduced exactly before the DSI term was substituted.\n")
L.append("Revised rows (composite with DSI term, deduplicated by composition):\n")
L.append("| Rank | Composition | V | ED | Cost | dV/V % | E_hull,charge | DSI | Cat. | Composite |\n|---|---|---|---|---|---|---|---|---|---|")
for i, r in enumerate(R["table10"], 1): L.append(f"| {i} | {r['Formula']} | {r['Avg Voltage (V)']:.3f} | {r['Energy Density (Wh/L)']:.0f} | {r['Cost per kWh ($/kWh)']:.0f} | {r['Max Volume Change (%)']:.1f} | {r['Stability Charge (eV)']:.3f} | {r['DSI']:.2f} | {r['DSI category'][0]} | {r['Composite (DSI term)']:.3f} |")
L.append("\n## 11. Supply-chain description (Section 4.2)\n")
L.append("Original: 'range 0.05-0.65, e.g. Li 0.60'. Revised: full element list (Co 0.95 ... Fe/P/Mg/Al/Si 0.05), Li and O excluded, range 0.05-0.95. Table values unchanged (verified: LiTi2O5 0.80, LiVO4 0.55, LiCu2O3 0.75, LiCoO3 0.05).\n")
L.append("## 12. Figures regenerated\n")
L.append("All 21 figures regenerated by `make_figures.py` and `make_umap.py` into `figures_revised/` (300 dpi, panel labels, 11-13 pt fonts). Fig. 1 is now a funnel; Figs 3, 5, 6, 9, 13, 14, 17, 18, 20 show the revised analyses described above; Figs 2, 4, 21 use the identifier-level dataset.\n")
L.append("## 13. Citations\n")
L.append("Added (verified via Crossref DOI registry): Meredig2018 (10.1039/C8ME00012C), Kapoor2023 (10.1016/j.patter.2023.100804). No existing entry altered or removed. The bib file is `rsc-2.bib`; main.tex calls `\\bibliography{rsc}`, so rename or symlink before compiling.\n")
open("/Users/thegreat/Desktop/Major revision /Numeric_Change_List.md", "w").write("\n".join(L)); print("change list written")
